namespace EFT.Ballistics
{
    public enum MaterialType
    {
        Asphalt = 1,
        Body,
        Cardboard,
        Chainfence,
        Concrete,
        Fabric,
        GarbageMetal,
        GarbagePaper,
        GenericSoft,
        Glass,
        GlassShattered,
        Grate,
        GrassHigh,
        GrassLow,
        Gravel,
        MetalThin,
        MetalThick,
        Mud,
        Pebbles,
        Plastic,
        Stone,
        Soil,
        SoilForest,
        Tile,
        Water,
        WaterPuddle,
        WoodThin,
        WoodThick,
        Tyre,
        Rubber,
        GenericHard,
        BodyArmor,
        Swamp,
        Helmet,
        GlassVisor,
        HelmetRicochet,
        MetalNoDecal,
        None = 0
    }
}
